AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Cloud formation for a DevOps Challenge

Resources:

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      DefinitionBody:
        swagger: '2.0'
        info:
          title: DevOps Challenge
          version: '1.0'
        paths:
          /api:
            get:
              responses:
                '200':
                  description: '200 response'
                  schema:
                    type: 'string'
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AddLambdaFunction.Arn}/invocations
                responses:
                  default:
                    statusCode: "200"
                passthroughBehavior: 'when_no_match'
                httpMethod: GET
                type: 'aws_proxy'
    
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api_publico.lambda_handler
      Runtime: python3.11
      CodeUri: ./lambda_api_functions/
      AutoPublishAlias: v1
      Policies:
      - Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: "*"

Outputs:
  ApiGateway:
    Description: API Gateway endpoint URL 
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/v1/api/"



