AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Cloud formation for a DevOps Challenge

Resources:

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: live
      DefinitionBody:
        swagger: '2.0'
        info:
          title: DevOps Challenge
          version: '1.0'
        paths:
          /api:
            get:
              responses:
                '200':
                  description: '200 response'
                  schema:
                    type: 'string'
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations
                passthroughBehavior: 'when_no_match'
                httpMethod: GET
                type: 'aws_proxy'
    
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api_publico.lambda_handler
      Runtime: python3.11
      CodeUri: ./lambda_api_functions/

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ApiFunction.Arn
      Action: lambda:InvokeFunction
      Principal: states.amazonaws.com
      SourceArn: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StateMachine}"
