name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Build and deploy
      run: |
        cd infra
        sam build --template-file template.yaml
        sam deploy --stack-name devops-challenge-stack --template-file template.yaml --capabilities CAPABILITY_IAM --region us-east-1 --s3-bucket devops-challenge-bucket-test
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  destroy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
       python-version: '3.11'

    - name: Destroy stack
      run: |
        aws cloudformation delete-stack --stack-name devops-challenge-stack
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}